### PR TITLE
Cleanup of README, pong.cpp

### PR DESCRIPTION
**Pull request by lethargilistic**
What up from reddit.

Before I get into my changes, if your contribution policy is to have people commit to a `test` branch, you should keep it up to date to avoid situations where your commits get mixed in with other people's PRs. :tongue: To make this a bit simpler, I recommend calling this branch the `dev` branch and having your `master` be called `release` instead. That way, there will be no confusion for yourself or others. You do the development for your next release on `dev`, then rebase `release` on `dev` when you're ready for a new release. :smile_cat: 

Anyway, I made your README's instructions clearer by adding section headers, a link to docs, and some syntax editing. You may also want to add instructions for the game here.

Next, I made pong.cpp more regular. It now has a shiftwidth of 4, entirely consistent indentation, and all of the if/else statements now have braces, as a guard against errors later on.

Lastly, I usually consider it a bad practice to have your first contribution to a project be stylistic/syntax changes, so I made a small, substantive change as a consolation. :sweat: I noticed you were hardcoding your own constant for pi. This was unnecessary because math.h comes with a M_PI constant that is correct to more decimal places than yours was. Leaning on language constants makes code easier to read and, in this case, more accurate anyway. ^^

### CODE REVIEW

**Comment by lethargilistic** [comment]
So, since there are merge conflicts, I really recommend that you rebase `test` on your `master` **before** merging this commit. There should be no conflicts between my branch and your `master`, and doing so will fix this problem.

**Comment by izz-j** [comment]
Okay I have changed the test and master to dev and release. This is actually my first time getting a pull request. I deleted the test branch and renamed it before I merged your changes to it (by accident) can you make another pull request and resubmit your changes to the dev branch? I fixed the merge issue. Thanks for the tips by the way

**Comment by lethargilistic** [comment]
Sure. For future, you could have done `git branch --move test dev`

**Comment by izz-j** [comment]
I wasn't aware I could do that. Thanks!

**Pull request closed without merging**
